### ISSUE TITLE
Concerning immediacy in IEEE 1275-1994

### ISSUE THREAD

**Issue by ruv** [mgcaret/of816#11]
I move here the [discussion](https://github.com/ForthHub/discussion/discussions/109#discussioncomment-1842443) from ForthHub:

@mgcaret wrote:
> > By the way, [`]`](https://forth-standard.org/standard/right-bracket) is an ordinary word (not immediate), but you seem [define it](https://github.com/mgcaret/of816/blob/8245ce322beb05f558b7f2c43dae07debd1012d1/asm/forth-dictionary.s#L1140) as immediate.
> 
> I don't seem to, I do. It even says why in the comments. OF816 is implemented follwing [IEEE 1275-1994](https://www.openbios.org/data/docs/of1275.pdf) (AKA "Open Firmware) and `]` is listed in "7.3.9.2.2 Immediate words," regardless of what any other standard might say.

It looks like the section 7.3.9.2.2 lists not immediate words, but the words that are connected to the immediacy mechanism in some way. For example, `state` and `compile,` are not immediate words by any means.

Also, have a look to the code **A** (in A.1.2.3 Type codes field):
> **A** ANS Forth word. In most cases, the description body for such words consists only of a one-line brief
description. The full specification is given by ANSI X3.215-1994

This code is specified for the word `]`, and it means that the full specification for this word should be taken from the Forth-94 standard ("ANS Forth", ANSI X3.215-1994).

So, immediacy should be corrected for some words in your system, I think.

**Comment by mgcaret** [comment]
I will look at the behavior for Sun OpenBoot and IBM SLOF and if they are in agreement I will go with what they agree with.  If they disagree I will go with whatever OpenBoot implements because it was the reference implementation when IEEE 1275-1994 was ratified.

**Comment by ruv** [comment]
> If they disagree I will go with whatever OpenBoot implements

Then you don't need to look at IBM SOLF at all ))


> it was the reference implementation when IEEE 1275-1994 was ratified

A really problem arises if in some place a reference implementation conflicts with the specifications. Another problem is that reference implementations usually overspecify requirements (and behavior). So the reference implementations are [not normative](https://forth-standard.org/proposals/reference-implementations-are-not-normative#contribution-187) anymore in the Forth standard.

Concerning the word `]` — it's implemented as an ordinary word in OpenBoot ([1](https://github.com/openbios/openboot/blob/master/obp/fm/kernel/interp.fth#L125), [2](https://github.com/openbios/openboot/blob/master/obp/fm/kernel/compiler.fth#L168)), and that is agree with all the specifications (both OpenFirmware and Forth-94).

It appears Open Firmware is made backward compatible with Forth-94 (see the sections 2.1, 2.4.3).  And for a number of words it just also defines semantics that are undefined by Forth-94.

**Comment by mgcaret** [comment]
My goal is to be [bug-compatible](https://en.wikipedia.org/wiki/Bug_compatibility?wprov=sfti1) with existing widespread implementations of 32-bit Open Firmware, so that code that runs on them has the same behavior when run on OF816.   E.g. If someone developed a 65816 system with SBUS slots, cards for SBUS Sun boxes should “just work.”

That being said, OF816’s core word set was developed following the descriptions of the behavior in the 1275-1994 document, not by looking at existing systems (even though I own several) as I wanted a somewhat clean approach.  I figured I would correct any issues that arise as the implementation grew and more code ran.   The device tree code from SLOF runs on OF816 with few changes (other than relying on SLOF-specific words), and has not revealed any problems with the immediacy or lack thereof of any words. 

I believe it is a leap to say that section 7.3.9.2.2 lists “the words that are connected to the immediacy mechanism in some way” when plainly read.  The title is literally “immediate words,” describes what immediate behavior is, and gives a list of words.  The errata do not correct or clarify this.  It may be a mistake by the authors of the standard, or poorly specified, and implementers simply ignored it.

Both SLOF (via qemu) and OpenBoot (Sun Ultra 45) seem to be in the latter camp so I will change the behavior.

**Comment by MitchBradley** [comment]
It is not correct to say that OpenBoot was the "reference implementation" for 1275-1995.  There was no official reference implementation, and Sun did not provide a freely-sharable version of the source code.  OpenBoot versions 1 and 2 predated ANS Forth.  The conversion to ANS Forth happened very late in the standards process.  I don't remember the exact timing but I do recall staying up late one night in a hotel hacking away, I believe at one of the final ANS meetings.   Apple's implementation was done from scratch based on a Forth system that Ron Hochsprung wrote or adapted.  I don't know much of the history of SLOF.  Anyway,  ] is not supposed to be immediate.  Section 7.3.9.2.2 is misleading.  It should probably be titled "Compilation Control" or something like that, and the introductory text changed.  But that document is historical, not living, so the change is not going to happen.

**Comment by ruv** [comment]
@MitchBradley, thank you for this interesting historical excursus ))

**Comment by mgcaret** [comment]
Thanks from me as well, @MitchBradley.  I guess, “inspired by” might be a better description of the relationship between OpenBoot and the standard?

**Comment by MitchBradley** [comment]
"Inspired by" is reasonably accurate; perhaps "adapted from" would be even better.

The detailed history is that I wrote OpenBoot at Sun. Another Sun employee, Paul Borrill, was heavily involved in IEEE standards, particularly Futurebus.  He encouraged me to start an IEEE committee to standardize Open Boot, and shepherded me through the process of getting IEEE project authorization.  This happened at the same time that the ANS Forth process was in its infancy.  I became chairman of the IEEE committee and joined the ANS committee, where I eventually, through attrition, became chair of the ANS Technical Subcommittee and vice chair of the overall ANS committee (Elizabeth Rather was Chair for the entire process). Sun had trademarked Open Boot and declined to release the name, so we adopted the new name Open Firmware.  Sun did release the Open Boot documentation (most of which I had written personally) for the purpose of using it as a jumping-off point for the new standard.

Soon after we started the IEEE committee, initially comprised of people from Sun and a few other Sun OEMs, Ron Hochsprung from Apple showed up at a meeting.  Ron had been using Forth for diagnostics at Apple for a long time, similar to how I had used Forth for diags at Sun.  When I first contemplated developing Open Boot, I had mentioned what I was doing to Ron, and apparently he had been keeping tabs on the development.  Apple had joined forces with IBM and Motorola to develop an open hardware specification for PowerPC.  It was called PREP - Power PC Reference Platform - but was later extended and renamed to CHRP - Common Hardware Reference Platform. Ron convinced them that they should base the PREP firmware on Open Firmware.  Representatives from IBM and Motorola soon joined the Open Firmware committee.

I had always intended that Open Boot be processor-independent, but of course I did not get everything right the first time.  With input from the PowerPC people and the Futurebus people, we managed to isolate assumptions about processors and buses into supplementary documents, leaving the "Core Requirements and Practices" document clean.

After the IEEE document was finalized, I helped Sun convert OpenBoot to become conformant with the IEEE standard.  I had left Sun to form my own company FirmWorks, but Sun and FirmWorks had cross-licensing agreements whereby we periodically synchronized code bases.  That became OpenBoot v3.  Sun continued to use its trademarked name OpenBoot, while the rest of the industry used the non-trademarked name Open Firmware.

**Comment by mgcaret** [comment]
@MitchBradley thanks again for that.  I feel like I should have known more of that history having been a Solaris admin for a good chunk of my career, along with a little bit of IBM POWER systems.

I have a new respect for the level of effort an undertaking like this is, but I have learned a ton.  I'm curious as to what you think of my little project.

**Comment by mgcaret** [comment]
I have reviewed the behavior of all words listed in 7.3.9.2.2 vs existing implementations, corrected ``]`` and believe that the others already have correct behavior.

**Comment by ruv** [comment]
Probably, a [comment](https://github.com/mgcaret/of816/blob/8245ce322beb05f558b7f2c43dae07debd1012d1/asm/forth-dictionary.s#L1313) for `COMPILE,` should be also removed in the same commit (or, otherwise a similar comment should be for `]` as well, but I suppose it would be wrong).
