### ISSUE TITLE
Signed comparisons involving minimum signed integer fail

### ISSUE THREAD

**Issue by mgcaret** [mgcaret/of816#4]
~~~
INCORRECT RESULT: T{ MIN-INT MAX-INT MAX -> MAX-INT }T OK
INCORRECT RESULT: T{ 0 MIN-INT MAX -> 0 }T OK
INCORRECT RESULT: T{ MAX-INT MIN-INT MAX -> MAX-INT }T OK
INCORRECT RESULT: T{ MIN-INT MAX-INT MIN -> MIN-INT }T OK
INCORRECT RESULT: T{ 0 MIN-INT MIN -> MIN-INT }T OK
INCORRECT RESULT: T{ MAX-INT MIN-INT MIN -> MIN-INT }T OK

INCORRECT RESULT: T{ MIN-INT MAX-INT < -> <TRUE> }T OK
INCORRECT RESULT: T{ 0 MIN-INT < -> <FALSE> }T OK
INCORRECT RESULT: T{ MAX-INT MIN-INT < -> <FALSE> }T OK
INCORRECT RESULT: T{ MIN-INT MAX-INT > -> <FALSE> }T OK
INCORRECT RESULT: T{ 0 MIN-INT > -> <TRUE> }T OK
INCORRECT RESULT: T{ MAX-INT MIN-INT > -> <TRUE> }T OK
INCORRECT RESULT: t{ min-int max-int >= -> <false> }t OK
INCORRECT RESULT: t{ max-int min-int >= -> <true> }t OK
~~~

**Comment by ksherlock** [comment]
https://github.com/mgcaret/of816/blob/30a8a259c7214eed94eb7e74aae27f047e9031b0/asm/mathlib.s#L7-L26

Just a thought... if the the signs differ, the two values will NEVER be equal and the negative one will be less.

    lda STACKBASE+2,x
    sec
    rol
    ; c = 1 if STACKBASE+2 is negative (and therefore < STACKBASE+6),
    ; Z must = 0 since C was rolled in
    rts

**Comment by mgcaret** [comment]
> Just a thought... if the the signs differ, the two values will NEVER be equal and the negative one will be less.

Sigh.  How many times have I looked at this and that should have been staring me in the eyes.

**Comment by mgcaret** [comment]
All comparison tests passing now.
